apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:step1
        resources: {}
        env:
        #- name: POSTGRES_HOST_AUTH_METHOD
          #value: trust
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - name: postgres
          containerPort: 5432 
      restartPolicy: Always
status: {}
